dependencies:
  - 'OpenZeppelin/openzeppelin-contracts@4.4.0'

compiler:
  solc:
    remappings:
      - '@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.4.0/contracts'
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.4.0/contracts'
