name: Release

on:
  release:
    types: [published]

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Run Compilation
        run: npm run compile
      - name: Publish to NPM
        run: npm publish
