name: Inventory system tests
on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'contracts/**'
      - 'test/**'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install JS/TS dependencies - this also installs smart contract dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Test
        run: forge test
